name: Backend CI

on:
  pull_request:
    types:
      - opened
    branches:
      - 'dev'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: cd BE && npm i
      
      - name: Build project
        run: cd BE && npm run build

      - name: Run ESLint and Prettier
        run: cd BE && npm run lint

      - name: Run tests
        run: cd BE && npm run test
