name: Frontend CI

on:
  pull_request:
    types:
      - opened
    branches:
      - 'dev'
    paths:
      - 'fe/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: cd fe && npm i
      
      - name: Build project
        run: cd fe && npm run build

      - name: Run ESLint and Prettier
        run: cd fe && npm run lint
